### ISSUE TITLE
Update Airbyte Helm chart configuration in ArgoCD

### ISSUE THREAD

**Issue by gregkonush** [gregkonush/lab#735]
## Overview

Need to update or configure the Airbyte Helm chart in ArgoCD.

## Current Configuration

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airbyte
helmCharts:
  - name: airbyte
    repo: https://airbyte.github.io/helm-charts
    version: 1.5.1
    releaseName: airbyte
    namespace: airbyte
    includeCRDs: true
```

## Tasks

* Review current Airbyte configuration
* Implement necessary changes
* Test changes in appropriate environment
* Deploy to production
